[project]
name = "zpp_store"
version = "0.1.3"
description = "Système de sérialisation de données"
mainfile = "__init__.py"
requires-python = ">=3.8"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "mit"
license_file = "LICENSE"
keywords = ["store","zephyroff"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3"]
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_store"
documentation = "https://github.com/ZephyrOff/zpp_store"

[project.dependencies]
PyYAML = "N.A"
msgpack = "N.A"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["PyYAML", "msgpack"]
includes = ["PyYAML"]
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
